services:

  app:
    image: ghcr.io/zarr888888/aquara_adminbackend_proyek2:latest
    container_name: laravel_app
    restart: always
    ports:
      - "8080:8000"
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: mysql:8.0
    container_name: laravel_db
    restart: always
    environment:
      MYSQL_DATABASE: aquara_proyek2
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravel123
      MYSQL_ROOT_PASSWORD: rootpasswordharusnyaunik
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db_data:

networks:
  app-network: